name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ls -la ~/.ssh

    - name: Start SSH Agent and Add Key
      run: |
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        ssh-add -l

    - name: Test SSH Connection
      run: ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@${{ secrets.VPS_HOST }} "echo 'SSH connection successful'"

    - name: Download docker-compose.yml to VPS
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@${{ secrets.VPS_HOST }} << 'EOF'
          wget -O /root/docker-compose.yml https://raw.githubusercontent.com/afonsoburginski/Easy/main/docker-compose.yaml
        EOF

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@${{ secrets.VPS_HOST }} << 'EOF'
          cd /root
          ls -la docker-compose.yml
          docker-compose down
          docker-compose pull
          docker-compose up -d
        EOF
