name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ls -la ~/.ssh
        cat ~/.ssh/id_rsa

    - name: Start SSH Agent and Add Key
      run: |
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        ssh-add -l
        ls -la ~/.ssh

    - name: Test SSH Connection
      run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@${{ secrets.VPS_HOST }} "echo 'SSH connection successful'"

    - name: Copy files via SCP
      run: |
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r . root@${{ secrets.VPS_HOST }}:/root/project

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /root/project
          docker-compose down
          docker pull afonsoburginski/taxi-rider-api
          docker pull afonsoburginski/taxi-driver-api
          docker pull afonsoburginski/taxi-admin-panel
          docker pull afonsoburginski/taxi-admin-api
          docker pull ridyio/delivery-gateway-box
          docker pull redis
          docker pull mysql:8.0.22
          docker-compose up -d
