name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.22
        env:
          MYSQL_ROOT_PASSWORD: defaultpassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker buildx build --platform linux/amd64 --push -t afonsoburginski/taxi-rider-api ./apps/rider-api
        docker buildx build --platform linux/amd64 --push -t afonsoburginski/taxi-driver-api ./apps/driver-api
        docker buildx build --platform linux/amd64 --push -t afonsoburginski/taxi-admin-api ./apps/admin-api
        docker buildx build --platform linux/amd64 --push -t afonsoburginski/taxi-admin-panel ./apps/admin-panel

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "."
        target: "/root/project"

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /root/project
          docker-compose down
          docker-compose pull
          docker-compose up -d
