name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push admin-api image
      run: |
        docker build -f ./apps/admin-api/Dockerfile -t afonsoburginski/taxi-admin-api .
        docker push afonsoburginski/taxi-admin-api

    - name: Build and push admin-panel image
      run: |
        docker build -f ./apps/admin-panel/Dockerfile -t afonsoburginski/taxi-admin-panel .
        docker push afonsoburginski/taxi-admin-panel

    - name: Build and push driver-api image
      run: |
        docker build -f ./apps/driver-api/Dockerfile -t afonsoburginski/taxi-driver-api .
        docker push afonsoburginski/taxi-driver-api

    - name: Build and push rider-api image
      run: |
        docker build -f ./apps/rider-api/Dockerfile -t afonsoburginski/taxi-rider-api .
        docker push afonsoburginski/taxi-rider-api

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        cat ~/.ssh/id_rsa  # Adiciona esta linha para verificar a chave

    - name: Test SSH Connection
      run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@${{ secrets.VPS_HOST }} "echo 'SSH connection successful'"

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "."
        target: "/root/project"

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /root/project
          docker-compose down
          docker pull afonsoburginski/taxi-rider-api
          docker pull afonsoburginski/taxi-driver-api
          docker pull afonsoburginski/taxi-admin-panel
          docker pull afonsoburginski/taxi-admin-api
          docker pull ridyio/delivery-gateway-box
          docker pull redis
          docker pull mysql:8.0.22
          docker-compose up -d
