name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ls -la ~/.ssh
        cat ~/.ssh/id_rsa

    - name: Start SSH Agent and Add Key
      run: |
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        ssh-add -l
        ls -la ~/.ssh

    - name: Test SSH Connection
      run: ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@${{ secrets.VPS_HOST }} "echo 'SSH connection successful'"

    - name: Copy docker-compose.yml to VPS
      run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa docker-compose.yml root@${{ secrets.VPS_HOST }}:/root/docker-compose.yml

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@${{ secrets.VPS_HOST }} << 'EOF'
          cd /root
          docker-compose down
          docker-compose pull
          docker-compose up -d
        EOF
